kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pizza-time-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30646
        hostPort: 30646
  - role: worker
  - role: worker
  - role: worker
